name: Deploy Bicep at Subscription Scope

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy main.bicep at subscription scope
        run: |
          az deployment sub create \
            --location eastus \
            --template-file ./main.bicep \
            --parameters resourceGroupName=myResourceGroup storagePrefix=mystgprefix location=eastus
